version: '3'

tasks:

  build:
    cmds:
      - |
        tinygo build -o hello-world.wasm \
          -scheduler=none \
          --no-debug \
          -target wasi ./main.go 
        ls -lh *.wasm
