image: k33g/capsule:0.0.2

tasks:
  - name: initialize
    before: |
      echo "🚀 before..."
    init: |
      echo "🚀 initialize..."
      # ------------------------------------
      # Install Couchbase
      # ------------------------------------
      #curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-amd64.deb
      #sudo dpkg -i ./couchbase-release-1.0-amd64.deb
      #sudo apt-get update
      #sudo apt-get install couchbase-server-community -y
      #rm ./couchbase-release-1.0-amd64.deb


ports:
  - port: 8080
    visibility: public
  - port: 3000
    visibility: public
  - port: 5000
    visibility: public
  - port: 7070
    visibility: public
  - port: 8091
    visibility: public

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
