version: '3'
# task install-mkdocs
# task serve-mkdocs
# task publish-mkdocs
# task release

tasks:
  # Generate the documentation
  # We use [mkdocs](https://www.mkdocs.org/)
  install-mkdocs:
    cmds:
      - pip install mkdocs-material
  serve-mkdocs:
    cmds:
      - mkdocs serve
  publish-mkdocs: # on the `main` branch
    cmds:
      - mkdocs gh-deploy

  # Generate a release of the capsule MDK
  # v0.3.4 🍋 [lemon]
  # `v0.3.4 🍋 [lemon]`: Capsule next generation (performances: x 10 🚀)
  # Then create the release manually on GitHub
  release:
    env:
      TAG: "v0.3.4"
      #TAG: "v0.3.5" # next release
    cmds:
      - echo "📦 Generating release..."
      - git add .
      - git commit -m "📦 updates HDK for ${TAG}"
      - git tag ${TAG}
      - git push origin main ${TAG}

  remove-tag:
    env:
      TAG: "v0.3.4"
    cmds:
      - git tag -d ${TAG}

  build-releases:
    env:
      TAG: "v0.3.4"
    cmds:
      - | 
        cd capsule-cli
        env GOOS=darwin GOARCH=arm64 go build -o capsule-${TAG}-darwin-arm64
        env GOOS=darwin GOARCH=amd64 go build -o capsule-${TAG}-darwin-amd64
        env GOOS=linux GOARCH=arm64 go build -o capsule-${TAG}-linux-arm64
        env GOOS=linux GOARCH=amd64 go build -o capsule-${TAG}-linux-amd64
        mv capsule-${TAG}-* ../release

      - |
        cd capsule-http
        env GOOS=darwin GOARCH=arm64 go build -o capsule-http-${TAG}-darwin-arm64
        env GOOS=darwin GOARCH=amd64 go build -o capsule-http-${TAG}-darwin-amd64
        env GOOS=linux GOARCH=arm64 go build -o capsule-http-${TAG}-linux-arm64
        env GOOS=linux GOARCH=amd64 go build -o capsule-http-${TAG}-linux-amd64
        mv capsule-http-${TAG}-* ../release


#replace github.com/bots-garden/capsule-host-sdk  => ../../capsule-host-sdk
#replace github.com/bots-garden/capsule-module-sdk => ../../capsule-module-sdk



