version: '3'
# task build-capsule-http build-hello-world test-hello-world
# task build-capsule-http build-hello-world test-hello-world-remote
# task stress-hello-world
# task build-capsule-http build-hey test-hey
# task stress-hey
# task build-capsule-http build-index-html test-index-html
# task stress-index-html

tasks:
  refresh-packages:
    cmds:
      - go get -u ./...

  # Build of capsule-http
  build-capsule-http:
    cmds:
      - |
        echo "ðŸ“¦ Building capsule-http..."
        go build -ldflags="-s -w" -o capsule-http
        ls -lh capsule-http

  build-hello-world:    
    cmds:
      - |
        echo "ðŸ“¦ Building hello-world.wasm module..."
        cd functions/hello-world
        tinygo build -o hello-world.wasm \
          -scheduler=none \
          --no-debug \
          -target wasi ./main.go 
        ls -lh *.wasm


  start-hello-world:
    env:
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        echo "ðŸš€ Testing hello-world..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT}


  call-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
    cmds:
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"

  health-hello-world:
    env:
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
    cmds:
      - | 
        curl -X GET ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}/health

  metrics-hello-world:
    env:
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
    cmds:
      - | 
        curl -X GET ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}/metrics


  # Testing capsule-http
  test-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        echo "ðŸš€ Testing hello-world..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"
      - killport ${HTTP_PORT}
  


  # ----------------------------------------
  # ðŸ³ Testing Docker image of capsule-http
  # ----------------------------------------
  test-hello-world-with-docker:
    env:
      JSON_DATA: '{"name":"ðŸ¤£ Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
      GOOS: "linux" 
      GOARCH: "arm64"
      IMAGE_BASE_NAME: "capsule-http"
      IMAGE_TAG: "0.4.0"
    cmds:
      - | 
        IMAGE_NAME="${IMAGE_BASE_NAME}-${GOOS}-${GOARCH}"
        echo "ðŸš€ Testing hello-world with ðŸ³..."
        echo "ðŸ–¼ï¸ ${IMAGE_NAME}"
        docker run \
          -p ${HTTP_PORT}:${HTTP_PORT} \
          -v $(pwd)/functions/hello-world:/app --rm ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} \
          /capsule-http \
          --wasm=./app/hello-world.wasm \
          --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"
      - |
        IMAGE_NAME="${IMAGE_BASE_NAME}-${GOOS}-${GOARCH}"
        docker stop $(docker ps -q --filter ancestor=${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} )

        #Use it with a remote file (to be tested):
        #docker run \
        #  -p 8080:8080 \
        #  -v $(pwd)/functions/hello-world:/app --rm ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG} \
        #  /capsule-http \
        #  --url=http://172.17.0.1:5000/hello-world.wasm \
        #  --wasm=./app/hello-world.wasm \
        #  --httpPort=8080


  test-hello-world-remote:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './tmp/hello-world.wasm'
      DOWNLOAD_URL: 'http://localhost:5000/hello-world.wasm'
    cmds:
      - |
        echo "ðŸŒ Serving the wasm file..."
        cd functions/hello-world
        echo "ðŸŒ you can download the wasm file with this url:"
        echo "http://localhost:5000/hello-world.wasm"
        python3 -m http.server 5000 &
        sleep 1
      - | 
        echo "ðŸš€ Testing hello-world..."
        ./capsule-http \
        --url=${DOWNLOAD_URL} \
        --wasm=${WASM_FILE} \
        --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"
      - killport ${HTTP_PORT}
      - pkill python3

  # Public GitLab Registry
  # task build-capsule-http
  run-hello-world-from-gitlab-registry:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './tmp/hello-world.wasm'
      GITLAB_WASM_PROJECT_ID: "45020306"
      WASM_PACKAGE: "capsule"
      WASM_MODULE: "hello-world.wasm"
      WASM_VERSION: "0.0.0"
    cmds:
      - | 
        DOWNLOAD_URL="https://gitlab.com/api/v4/projects/${GITLAB_WASM_PROJECT_ID}/packages/generic/${WASM_PACKAGE}/${WASM_VERSION}/${WASM_MODULE}"
        echo "ðŸš€ Testing hello-world..."
        echo "${DOWNLOAD_URL}"
        ./capsule-http \
        --url=${DOWNLOAD_URL} \
        --wasm=${WASM_FILE} \
        --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"
      - killport ${HTTP_PORT}

  run-hello-world-from-private-gitlab-registry:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './tmp/hello-world.wasm'
      GITLAB_WASM_PROJECT_ID: "46123319"
      WASM_PACKAGE: "capsule"
      WASM_MODULE: "hello-world.wasm"
      WASM_VERSION: "0.0.0"
    cmds:
      - | 
        DOWNLOAD_URL="https://gitlab.com/api/v4/projects/${GITLAB_WASM_PROJECT_ID}/packages/generic/${WASM_PACKAGE}/${WASM_VERSION}/${WASM_MODULE}"
        echo "ðŸš€ Testing hello-world..."
        echo "${DOWNLOAD_URL}"
        ./capsule-http \
        --url=${DOWNLOAD_URL} \
        --authHeaderName="PRIVATE-TOKEN" \
        --authHeaderValue="${GITLAB_WASM_TOKEN}" \
        --wasm=${WASM_FILE} \
        --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"
      - killport ${HTTP_PORT}


  # serving capsule-http
  serve-hello-world:
    env:
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        echo "ðŸš€ Serving hello-world..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1

  # serving capsule-http with ngrok
  serve-ngrok-hello-world:
    env:
      HTTP_PORT: '6666'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        echo "ðŸš€ Serving hello-world..."
        NGROK_AUTHTOKEN="${NGROK_AUTHTOKEN}" ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1


  # killing capsule-http
  kill-capsule-http:
    cmds:
      - | 
        echo "ðŸš€ Killing hello-world..."
        pkill capsule-http

  # query capsule-http
  query-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
    cmds:
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"

  # query capsule-http with ngrok
  query-ngrok-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
    cmds:
      - | 
        NGROK_URL="$(cat ngrok.url)"
        echo "ðŸŒ ${NGROK_URL}"
        curl -X POST ${NGROK_URL} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"

  # metrics capsule-http
  metrics-hello-world:
    env:
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
    cmds:
      - | 
        curl ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}/metrics


  stress-average-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      #WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        #hey -n 300 -c 1 -m POST \
        #hey -n 300 -c 100 -m POST \
        hey -n 1596 -c 1 -m POST \
        -H "Content-Type: application/json; charset=utf-8" \
        -d "${JSON_DATA}" ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}

  stress-high-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        hey -n 10000 -c 6000 -m POST \
        -H "Content-Type: application/json; charset=utf-8" \
        -d "${JSON_DATA}" ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}



  # grafana/grafana-oss
  # docker run -d -p 3000:3000 grafana/grafana-oss

  # task build-capsule-http
  # task build-hello-world
  # task stress-hello-world
  stress-hello-world:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
      HTTP_PORT: '6666'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hello-world/hello-world.wasm'
    cmds:
      - | 
        echo "ðŸš€ Stressing hello-world..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        hey -n 300 -c 100 -m POST \
        -H "Content-Type: application/json; charset=utf-8" \
        -d "${JSON_DATA}" ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} > capsule.http.stress.report.0.4.0.txt
      #- killport ${HTTP_PORT}

  build-hey:
    cmds:
      - |
        echo "ðŸ“¦ Building hey.wasm module..."
        cd functions/hey
        tinygo build -o hey.wasm \
          -scheduler=none \
          --no-debug \
          -target wasi ./main.go 
        ls -lh *.wasm

  test-hey:
    env:
      DATA: 'Bob Morane'
      HTTP_PORT: '8888'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hey/hey.wasm'
    cmds:
      - | 
        echo "ðŸš€ Testing hey..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: text/plain; charset=utf-8' \
          -d "${DATA}"
      - killport ${HTTP_PORT}

  stress-hey:
    env:
      DATA: 'Bob Morane'
      HTTP_PORT: '8080'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/hey/hey.wasm'
    cmds:
      - | 
        echo "ðŸš€ Stressing hey..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        hey -n 300 -c 100 -m POST \
        -H "Content-Type: text/plain; charset=utf-8" \
        -d "${DATA}" ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}
      - killport ${HTTP_PORT}


  build-index-html:
    cmds:
      - |
        echo "ðŸ“¦ Building index-html.wasm module..."
        cd functions/index-html
        tinygo build -o index.wasm \
          -scheduler=none \
          --no-debug \
          -target wasi ./main.go 
        ls -lh *.wasm

  start-index-html:
    env:
      HTTP_PORT: '7777'
      WASM_FILE: './functions/index-html/index.wasm'
    cmds:
      - | 
        echo "ðŸš€ Testing hey..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT}



  test-index-html:
    env:
      DATA: 'Bob Morane'
      HTTP_PORT: '7777'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/index-html/index.wasm'
    cmds:
      - | 
        echo "ðŸš€ Testing hey..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        curl -v ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} 
      - killport ${HTTP_PORT}

  stress-index-html:
    env:
      HTTP_PORT: '8080'
      DOMAIN: 'localhost'
      PROTOCOL: 'http'
      WASM_FILE: './functions/index-html/index.wasm'
    cmds:
      - | 
        echo "ðŸš€ Stressing hey..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT} &
        sleep 1
      - | 
        hey -n 300 -c 100 -m GET \
        ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}
      - killport ${HTTP_PORT}

