version: "3"

services:
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto:2
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - "9001:9001"
      - "1883:1883"