image: k33g/capsule:0.0.1

tasks:
  - name: initialize
    before: |
      CAPSULE_VERSION="0.1.4"
      echo "💊 Installing capsule..."
      wget https://github.com/bots-garden/capsule/releases/download/${CAPSULE_VERSION}/capsule-${CAPSULE_VERSION}-linux-amd64.tar.gz
      sudo tar -zxf capsule-${CAPSULE_VERSION}-linux-amd64.tar.gz --directory /usr/local/bin
      rm capsule-${CAPSULE_VERSION}-linux-amd64.tar.gz
    init: |
      echo "🚀 ..."


ports:
  - port: 3000-25000
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - golang.go
    - pkief.material-icon-theme
    - aaron-bond.better-comments
