version: '3'

description: >
  # Integration tests with Redis
  
  - Build the wasm module: `task build-wasm`
  - Build capsule-http: `task build-capsule-http`
  - Start Redis: `task start-redis`
  - Start Hello People: `task start`
  - Call the function/service: `task call`
  - Get the Metrics: `task metrics`
  - Run load test: `task stress`
  - Test Health check: `task health-check`
  - Stop Redis: `task stop-redis`

env:
    HTTP_PORT: '8070'
    DOMAIN: 'localhost'
    PROTOCOL: 'http'
    WASM_FILE: './hello-people.wasm'

tasks:
  build-wasm:
    cmds:
      - |
        tinygo build -o hello-people.wasm \
          -scheduler=none \
          --no-debug \
          -target wasi ./main.go 
        ls -lh *.wasm

  # Build of capsule-http
  build-capsule-http:
    cmds:
      - |
        echo "📦 Building capsule-http..."
        cd ../..
        go build -ldflags="-s -w" -o capsule-http
        ls -lh capsule-http
        mv capsule-http ./functions/hello-people

  start-redis:
    cmds:
      - sudo systemctl start redis-server

  stop-redis:
    cmds:
      - sudo systemctl stop redis-server

  start:
    cmds:
      - | 
        echo "🚀 Testing hello-people..."
        ./capsule-http --wasm=${WASM_FILE} --httpPort=${HTTP_PORT}

  call:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
    cmds:
      - | 
        curl -X POST ${PROTOCOL}://${DOMAIN}:${HTTP_PORT} \
          -H 'Content-Type: application/json; charset=utf-8' \
          -d "${JSON_DATA}"
        echo ""

  metrics:
    cmds:
      - | 
        curl -X GET ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}/metrics
        echo ""

  health-check:
    cmds:
      - | 
        curl -X GET ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}/health
        echo ""

  stress:
    env:
      JSON_DATA: '{"name":"Bob Morane","age":42}'
    cmds:
      - | 
        #hey -n 300 -c 1 -m POST \
        #hey -n 300 -c 100 -m POST \
        #hey -n 1596 -c 1 -m POST \
        #hey -n 15 -c 1 -m POST \
        hey -n 3000 -c 100 -m POST \
        -H "Content-Type: application/json; charset=utf-8" \
        -d "${JSON_DATA}" ${PROTOCOL}://${DOMAIN}:${HTTP_PORT}
