hello:
    default:
        - http://localhost:9091
        - http://localhost:7071

hey:
    default:
        - http://localhost:9092

hola:
    default:
        - http://localhost:9093
    orange:
        - http://localhost:6061
    yellow:
        - http://localhost:6062
