name: Release Capsule Binaries

on:
  release:
    types: [created]

jobs:

  releases-matrix-launcher:
    name: Release Capsule (Launcher) Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./capsule-launcher"
          binary_name: "capsule"
          ldflags: "-s -w"
          #extra_files: ./capsulelauncher/README.md
          goversion: "https://dl.google.com/go/go1.18.4.linux-amd64.tar.gz"
